test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,9 +1,17 @@
 name: Python CI
 
+# when push the code into branch will trigger the workflow
+# on:
+#   push:
+#     branches:
+#       - dev
+
 on:
-  push:
-    branches:
-      - dev
+  pull_request:
+    types:
+      - opened
+      - synchronize
+  workflow_dispatch:
 
 jobs:
   build-and-test:
@@ -24,13 +32,14 @@ jobs:
       with:
         # Inside with parameters are ssh need the values
         host: ${{ secrets.DEV_GCP_INSTANCE_IP }}
-        # script instance
-        # host: ${{ secrets.SCRIPT_INSTANCE_IP }}
         username: james
         key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
-        # script instance
-        # key: ${{ secrets.SCRIPT_INSTANCE_SSH_PRIVATE }}
         script: |
+
+          sudo docker exec veriscope-internal-laravel.test-1 sh -c "cd /opt/veriscope && git checkout james-unittest-postmanAPI && git pull origin james-unittest-postmanAPI"
+          sudo docker exec veriscope-internal-laravel.test-1 sh -c "cd /opt/veriscope/veriscope_ta_dashboard && composer install && php artisan migrate && php artisan config:clear && php artisan cache:clear && npm run dev"
+          sudo docker exec veriscope-internal-laravel.test-1 sh -c "cd /opt/veriscope/veriscope_ta_node && npm install && systemctl restart ta-node-1"
+          if [ $? -ne 0 ]; then exit 1; fi
 
           # Create file for docker used
           sudo docker exec veriscope-internal-laravel.test-1 sh -c "echo '${{ secrets.DEV_TEST_URL }} ${{ secrets.DEV_API_AUTH_TOKEN }} ${{ secrets.DEV_SSH_PRIVATE_KEY }}' > pytest_value.txt"
@@ -38,16 +47,16 @@ jobs:
           sudo docker exec -i veriscope-internal-laravel.test-1 pytest /opt/veriscope/tests
           if [ $? -ne 0 ]; then exit 1; fi
           # Testing end-to-end
-          sudo docker exec -i veriscope-internal-laravel.test-1 pytest -k test_get_jurisdictions /opt/veriscope/API-Docs/API-Testing/postman-collection-API-testing/postman-collection-positive-test/test_postman_endpoint_success.py4
+          sudo docker exec -i veriscope-internal-laravel.test-1 pytest -k test_get_jurisdictions /opt/veriscope/API-Docs/API-Testing/postman-collection-API-testing/postman-collection-positive-test/test_postman_endpoint_success.py
           if [ $? -ne 0 ]; then exit 1; fi
 
           sudo docker exec veriscope-internal-laravel.test-1 sh -c "rm pytest_value.txt"
     # Use if condition to prevent push on test failure
-    - name: Prevent Push on Test Failure
-      if: ${{ failure() }}
-      run: |
-        echo "Tests failed. Preventing push to branch."
-        continue-on-error: false
+    # - name: Prevent Push on Test Failure
+    #   if: ${{ failure() }}
+    #   run: |
+    #     echo "Tests failed. Preventing push to branch."
+    #     continue-on-error: false
 # job name
   # push-if-tests-pass:
   #   needs: build-and-test
@@ -62,12 +71,6 @@ jobs:
   #     with:
   #       branch: dev
   #       github_token: ${{ secrets.MY_TOKEN }}
-
-
- 
-# sudo docker exec veriscope-internal-laravel.test-1 sh -c "cd /opt/veriscope && git checkout main && git pull origin main"
-#           sudo docker exec veriscope-internal-laravel.test-1 sh -c "cd /opt/veriscope/veriscope_ta_dashboard && composer install && php artisan migrate && php artisan config:clear && php artisan cache:clear && npm run dev"
-#           sudo docker exec veriscope-internal-laravel.test-1 sh -c "cd /opt/veriscope/veriscope_ta_node && npm install && systemctl restart ta-node-1"
 
     # - name: Set up Python
     #   uses: actions/setup-python@v2
